---
- name: Deploy Activist Application
  hosts: all
  vars:
    project_dir: "/root/activist"
    frontend_dir: "{{ project_dir }}/frontend"
  become: true

  handlers:
    - name: Debug Docker installation output
      ansible.builtin.debug:
        var: docker_install

  tasks:
    - name: Wait for APT locks to be released
      ansible.builtin.shell: |
        while lsof /var/lib/dpkg/lock-frontend >/dev/null 2>&1 || lsof /var/lib/apt/lists/lock >/dev/null 2>&1 || lsof /var/lib/dpkg/lock >/dev/null 2>&1; do
          sleep 5
        done
      changed_when: false

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      register: apt_update
      retries: 5
      delay: 30
      until: apt_update is success

    - name: Install required packages
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - git
          - yarn
        state: present
        update_cache: true
      register: apt_result
      retries: 5
      delay: 30
      until: apt_result is success

    - name: Add Docker GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu noble stable"
        state: present
        update_cache: true

    - name: Wait for APT locks before Docker install
      ansible.builtin.shell: |
        while lsof /var/lib/dpkg/lock-frontend >/dev/null 2>&1 || lsof /var/lib/apt/lists/lock >/dev/null 2>&1 || lsof /var/lib/dpkg/lock >/dev/null 2>&1; do
          sleep 5
        done
      changed_when: false

    - name: Install Docker packages
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: true
      register: docker_install
      retries: 5
      delay: 30
      until: docker_install is success

    - name: Wait for Docker to be installed
      ansible.builtin.wait_for:
        path: /usr/bin/docker
        timeout: 60

    - name: Enable and start Docker service
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: true
        daemon_reload: true
      register: docker_service
      retries: 3
      delay: 10
      until: docker_service is success

    - name: Clone application repository
      ansible.builtin.git:
        repo: "https://github.com/aasimsyed/activist.git"
        dest: "{{ project_dir }}"
        version: main
        force: true

    - name: Setup Node.js repository
      ansible.builtin.uri:
        url: https://deb.nodesource.com/setup_20.x
        return_content: true
      register: node_setup

    - name: Execute Node.js setup script
      ansible.builtin.shell: "{{ node_setup.content }}"
      args:
        executable: /bin/bash
      changed_when: false

    - name: Install Node.js
      ansible.builtin.apt:
        name: nodejs
        state: present
        update_cache: true
      environment:
        DEBIAN_FRONTEND: "noninteractive"
      register: nodejs_install
      retries: 3
      delay: 10
      until: nodejs_install is success

    - name: Update npm to latest version
      ansible.builtin.shell: |
        npm install -g npm@latest
      changed_when: false

    - name: Ensure Corepack is enabled system-wide
      become: true
      ansible.builtin.shell: |
        corepack enable --install
        corepack prepare yarn@4.6.0 --activate
      args:
        executable: /bin/bash
      environment:
        PATH: "/usr/local/bin:/usr/bin:/bin:{{ ansible_env.PATH }}"
      changed_when: false

    - name: Set project-specific Yarn version
      community.general.yarn:
        path: "{{ frontend_dir }}"
        version: 4.6.0
      environment:
        PATH: "/usr/local/bin:/usr/bin:/bin:{{ ansible_env.PATH }}"

    - name: Install dependencies with zero-installs
      ansible.builtin.shell: |
        set -eo pipefail
        cd {{ frontend_dir }} 2>&1
        yarn install --immutable --frozen-lockfile 2>&1 | tee -a yarn_install.log
      args:
        chdir: "{{ frontend_dir }}"
        executable: /bin/bash
      environment:
        PATH: "/usr/local/bin:/usr/bin:/bin:{{ ansible_env.PATH }}"
        YARN_ENABLE_INLINE_BUILDS: "1"
        YARN_ENABLE_LOGS: "0"
      async: 600
      poll: 15
      register: yarn_install
      retries: 2
      delay: 30
      until: yarn_install is success
      changed_when: false

    - name: Wait for Yarn migration to complete
      ansible.builtin.async_status:
        jid: "{{ yarn_migration.ansible_job_id }}"
      register: yarn_job_result
      until: yarn_job_result.finished
      retries: 30
      delay: 30  # Total wait: 30*30=900s (15min)

    - name: Validate Yarn migration success
      ansible.builtin.fail:
        msg: "Yarn migration failed after 15 minutes"
      when: yarn_job_result.failed

    - name: Flush handlers
      ansible.builtin.meta: flush_handlers

    - name: Create Python virtual environment
      ansible.builtin.command:
        cmd: python3 -m venv venv
        chdir: "{{ project_dir }}"
        creates: "{{ project_dir }}/venv/bin/activate"

    - name: Install Python dependencies
      ansible.builtin.pip:
        requirements: "{{ project_dir }}/backend/requirements-dev.txt"
        virtualenv: "{{ project_dir }}/venv"
        state: present

    - name: Configure backend port binding
      ansible.builtin.lineinfile:
        path: "{{ project_dir }}/docker-compose.yml"
        regexp: '("${BACKEND_PORT}:${BACKEND_PORT}")'
        line: '"0.0.0.0:\1"'
        backrefs: true

    - name: Configure frontend port binding
      ansible.builtin.lineinfile:
        path: "{{ project_dir }}/docker-compose.yml"
        regexp: '("${FRONTEND_PORT}:${FRONTEND_PORT}")'
        line: '"0.0.0.0:\1"'
        backrefs: true

    - name: Deploy backend and database first
      community.docker.docker_compose_v2:
        project_src: "{{ project_dir }}"
        env_files:
          - .env.dev
        services:
          - backend
          - db
        build: always
        state: present

    - name: Deploy full application stack
      community.docker.docker_compose_v2:
        project_src: "{{ project_dir }}"
        files:
          - docker-compose.yml
        state: present
        pull: "always"
        remove_orphans: true
        build: "always"
      register: compose_result
      until: compose_result is success
      retries: 3
      delay: 10
