---
- name: Install mutagen
  when: ansible_system == 'Darwin'
  community.general.homebrew:
    name: mutagen-io/mutagen/mutagen
    state: present

- name: Create mutagen config directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.mutagen"
    state: directory
    mode: '0755'

- name: Configure mutagen sync
  ansible.builtin.template:
    src: mutagen.yml.j2
    dest: "{{ ansible_env.HOME }}/.mutagen/mutagen.yml"
    mode: '0600'

- name: Create dev sync script
  ansible.builtin.template:
    src: dev-sync.sh.j2
    dest: "{{ ansible_env.HOME }}/bin/dev-sync"
    mode: '0755'
